CREATE TABLE ACTIVITY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    TITLE VARCHAR(50) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    FEE NUMERIC NOT NULL,
    BALANCE NUMERIC NOT NULL,
    CREATED_TIMESTAMP TIMESTAMP NOT NULL,
    UPDATED_TIMESTAMP TIMESTAMP NOT NULL,
    PRIMARY KEY(ID)
);